name: Backend-Deployment

on:
  push: 
    branches: 
      - prod
    paths: 
      - 'api/**'
      - '.github/workflows/api-cd.yml'

jobs: 
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    env:
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with: 
          context: ./api
          file: ./api/docker/Dockerfile.prod
          push: true
          tags: |
            ikrambagban/medical-record-api:${{ github.sha }}
            ikrambagban/medical-record-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            
            echo "Pulling latest Docker image..."
            docker pull ikrambagban/medical-record-api:${{ github.sha }}

            echo "Stopping and removing existing container..."
            docker stop medical-record-api || true
            docker rm medical-record-api || true

            echo "Starting new container..."
            docker run -d \
              --restart unless-stopped \
              --name medical-record-api \
              -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
              -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
              -e AWS_REGION="${{ secrets.AWS_REGION }}" \
              -e S3_BUCKET_NAME="${{ secrets.S3_BUCKET_NAME }}" \
              -e CLOUDFRONT_DISTRIBUTION_URL="${{ secrets.CLOUDFRONT_DISTRIBUTION_URL }}" \
              -e RESEND_FROM_EMAIL="${{ secrets.RESEND_FROM_EMAIL }}" \
              -e RESEND_API_KEY="${{ secrets.RESEND_API_KEY }}" \
              -e NODE_ENV="${{ secrets.NODE_ENV }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e SENDGRID_API_KEY="${{ secrets.SENDGRID_API_KEY }}" \
              -e SENDGRID_FROM_EMAIL="${{ secrets.SENDGRID_FROM_EMAIL }}" \
              -e REDIS_URL="${{ secrets.REDIS_URL }}" \
              -p 4000:3000 \
              ikrambagban/medical-record-api:${{ github.sha }}
