name: API Build and Test

on:
  push:
    branches: ['**'] 
    paths:
      - 'api/**'
      - '.github/workflows/api-ci.yml'
      
  pull_request:
    branches: ['**']
    paths:
      - 'api/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CLOUDFRONT_DISTRIBUTION_URL: ${{ secrets.CLOUDFRONT_DISTRIBUTION_URL }}
      RESEND_FROM_EMAIL: ${{ secrets.RESEND_FROM_EMAIL }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENDGRID_FROM_EMAIL: ${{ secrets.SENDGRID_FROM_EMAIL }}
      REDIS_URL: ${{ secrets.REDIS_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.1

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Check Formatting
        run: pnpm run format:check

      - name: Check Linting
        run: pnpm run lint:check

      - name: Run Tests
        run: pnpm run test